-- MySQL Script generated by MySQL Workbench
-- Mon Mar 24 12:54:18 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema jehovarafa
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema jehovarafa
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `jehovarafa` DEFAULT CHARACTER SET utf8mb4 ;
USE `jehovarafa` ;

-- -----------------------------------------------------
-- Table `jehovarafa`.`rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jehovarafa`.`rol` (
  `id_rol` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(25) CHARACTER SET 'latin1' NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `descripción` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_rol`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `jehovarafa`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jehovarafa`.`usuario` (
  `id_usuario` INT(11) NOT NULL AUTO_INCREMENT,
  `id_rol` INT(11) NOT NULL,
  `imagen` VARCHAR(255) NOT NULL,
  `usuario` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL,
  `correo` VARCHAR(100) NOT NULL,
  `password` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL,
  `estado` VARCHAR(25) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL,
  PRIMARY KEY (`id_usuario`),
  INDEX `id_rol` (`id_rol` ASC) VISIBLE,
  CONSTRAINT `usuario_ibfk_1`
    FOREIGN KEY (`id_rol`)
    REFERENCES `jehovarafa`.`rol` (`id_rol`))
ENGINE = InnoDB
AUTO_INCREMENT = 41
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `jehovarafa`.`bitacora`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jehovarafa`.`bitacora` (
  `id_bitacora` INT(11) NOT NULL AUTO_INCREMENT,
  `id_usuario` INT(11) NOT NULL,
  `tabla` VARCHAR(30) NOT NULL,
  `actividad` TEXT NOT NULL,
  `fecha_hora` DATETIME NOT NULL,
  PRIMARY KEY (`id_bitacora`),
  INDEX `id_usuario` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `bitacora_ibfk_1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `jehovarafa`.`usuario` (`id_usuario`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `jehovarafa`.`categoria_servicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jehovarafa`.`categoria_servicio` (
  `id_categoria` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(25) NOT NULL,
  `estado` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`id_categoria`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `jehovarafa`.`especialidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jehovarafa`.`especialidad` (
  `id_especialidad` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(25) CHARACTER SET 'latin1' NOT NULL,
  `estado` VARCHAR(20) NOT NULL,
  PRIMARY KEY USING BTREE (`id_especialidad`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `jehovarafa`.`personal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jehovarafa`.`personal` (
  `id_personal` INT(11) NOT NULL AUTO_INCREMENT,
  `nacionalidad` VARCHAR(5) NOT NULL,
  `cedula` VARCHAR(20) NOT NULL,
  `nombre` VARCHAR(25) NOT NULL,
  `apellido` VARCHAR(25) NOT NULL,
  `telefono` VARCHAR(20) NOT NULL,
  `email` VARCHAR(25) NOT NULL,
  `tipodecategoria` VARCHAR(25) NOT NULL,
  `id_especialidad` INT(11) NULL DEFAULT NULL,
  `id_usuario` INT(11) NOT NULL,
  PRIMARY KEY (`id_personal`),
  UNIQUE INDEX `cedula` (`cedula` ASC) VISIBLE,
  INDEX `id_especialidad` (`id_especialidad` ASC, `id_usuario` ASC) VISIBLE,
  INDEX `id_usuario` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `personal_ibfk_1`
    FOREIGN KEY (`id_especialidad`)
    REFERENCES `jehovarafa`.`especialidad` (`id_especialidad`),
  CONSTRAINT `personal_ibfk_2`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `jehovarafa`.`usuario` (`id_usuario`))
ENGINE = InnoDB
AUTO_INCREMENT = 17
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `jehovarafa`.`paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jehovarafa`.`paciente` (
  `id_paciente` INT(11) NOT NULL AUTO_INCREMENT,
  `nacionalidad` VARCHAR(12) NOT NULL,
  `cedula` VARCHAR(25) CHARACTER SET 'latin1' NOT NULL,
  `nombre` VARCHAR(25) CHARACTER SET 'latin1' NOT NULL,
  `apellido` VARCHAR(25) CHARACTER SET 'latin1' NOT NULL,
  `telefono` VARCHAR(25) CHARACTER SET 'latin1' NOT NULL,
  `direccion` TEXT CHARACTER SET 'latin1' NOT NULL,
  `fn` DATE NOT NULL,
  `estado` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`id_paciente`))
ENGINE = InnoDB
AUTO_INCREMENT = 22
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `jehovarafa`.`serviciomedico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jehovarafa`.`serviciomedico` (
  `id_servicioMedico` INT(11) NOT NULL AUTO_INCREMENT,
  `id_categoria` INT(11) NOT NULL,
  `id_personal` INT(11) NOT NULL,
  `precio` FLOAT(12,2) NOT NULL,
  `estado` VARCHAR(25) CHARACTER SET 'latin1' NOT NULL,
  `paciente_id_paciente` INT(11) NOT NULL,
  PRIMARY KEY (`id_servicioMedico`),
  INDEX `id_doctor` (`id_personal` ASC) VISIBLE,
  INDEX `id_categoria` (`id_categoria` ASC) VISIBLE,
  INDEX `fk_serviciomedico_paciente1_idx` (`paciente_id_paciente` ASC) VISIBLE,
  CONSTRAINT `serviciomedico_ibfk_2`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `jehovarafa`.`categoria_servicio` (`id_categoria`),
  CONSTRAINT `serviciomedico_ibfk_3`
    FOREIGN KEY (`id_personal`)
    REFERENCES `jehovarafa`.`personal` (`id_personal`),
  CONSTRAINT `fk_serviciomedico_paciente1`
    FOREIGN KEY (`paciente_id_paciente`)
    REFERENCES `jehovarafa`.`paciente` (`id_paciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 20
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `jehovarafa`.`cita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jehovarafa`.`cita` (
  `id_cita` INT(11) NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `hora` TIME NOT NULL,
  `estado` VARCHAR(25) CHARACTER SET 'latin1' NOT NULL,
  `serviciomedico_id_servicioMedico` INT(11) NOT NULL,
  PRIMARY KEY (`id_cita`),
  INDEX `fk_cita_serviciomedico1_idx` (`serviciomedico_id_servicioMedico` ASC) VISIBLE,
  CONSTRAINT `fk_cita_serviciomedico1`
    FOREIGN KEY (`serviciomedico_id_servicioMedico`)
    REFERENCES `jehovarafa`.`serviciomedico` (`id_servicioMedico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 40
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `jehovarafa`.`control`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jehovarafa`.`control` (
  `id_control` INT(11) NOT NULL AUTO_INCREMENT,
  `id_paciente` INT(11) NOT NULL,
  `id_usuario` INT(11) NOT NULL,
  `diagnostico` TEXT CHARACTER SET 'latin1' NOT NULL,
  `medicamentosRecetados` TEXT CHARACTER SET 'latin1' NOT NULL,
  `fecha_control` DATETIME NOT NULL,
  `fechaRegreso` DATE NOT NULL,
  `nota` VARCHAR(40) NOT NULL,
  `estado` VARCHAR(25) CHARACTER SET 'latin1' NOT NULL,
  PRIMARY KEY (`id_control`),
  INDEX `id_paciente` (`id_paciente` ASC, `id_usuario` ASC) VISIBLE,
  INDEX `id_usuario` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `control_ibfk_1`
    FOREIGN KEY (`id_paciente`)
    REFERENCES `jehovarafa`.`paciente` (`id_paciente`),
  CONSTRAINT `control_ibfk_2`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `jehovarafa`.`usuario` (`id_usuario`))
ENGINE = InnoDB
AUTO_INCREMENT = 26
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `jehovarafa`.`proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jehovarafa`.`proveedor` (
  `id_proveedor` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(25) CHARACTER SET 'latin1' NOT NULL,
  `rif` VARCHAR(25) CHARACTER SET 'latin1' NOT NULL,
  `telefono` VARCHAR(25) CHARACTER SET 'latin1' NOT NULL,
  `email` VARCHAR(40) NOT NULL,
  `direccion` TEXT NOT NULL,
  `estado` VARCHAR(25) CHARACTER SET 'latin1' NOT NULL,
  PRIMARY KEY (`id_proveedor`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `jehovarafa`.`entrada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jehovarafa`.`entrada` (
  `id_entrada` INT(11) NOT NULL AUTO_INCREMENT,
  `id_proveedor` INT(11) NOT NULL,
  `numero_de_lote` INT(16) NOT NULL,
  `fechaDeIngreso` DATE NOT NULL,
  `estado` VARCHAR(10) CHARACTER SET 'latin1' NOT NULL,
  PRIMARY KEY (`id_entrada`),
  INDEX `id_proveedor` (`id_proveedor` ASC) VISIBLE,
  CONSTRAINT `entrada_ibfk_1`
    FOREIGN KEY (`id_proveedor`)
    REFERENCES `jehovarafa`.`proveedor` (`id_proveedor`))
ENGINE = InnoDB
AUTO_INCREMENT = 38
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `jehovarafa`.`insumo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jehovarafa`.`insumo` (
  `id_insumo` INT(11) NOT NULL AUTO_INCREMENT,
  `imagen` VARCHAR(500) CHARACTER SET 'latin1' NOT NULL,
  `nombre` VARCHAR(25) CHARACTER SET 'latin1' NOT NULL,
  `descripcion` TEXT CHARACTER SET 'latin1' NOT NULL,
  `precio` FLOAT(12,2) NOT NULL,
  `cantidad` INT(11) NOT NULL,
  `stockMinimo` INT(11) NOT NULL,
  `estado` VARCHAR(25) CHARACTER SET 'latin1' NOT NULL,
  PRIMARY KEY (`id_insumo`))
ENGINE = InnoDB
AUTO_INCREMENT = 24
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `jehovarafa`.`entrada_insumo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jehovarafa`.`entrada_insumo` (
  `id_entradaDeInsumo` INT(11) NOT NULL AUTO_INCREMENT,
  `id_insumo` INT(11) NOT NULL,
  `id_entrada` INT(11) NOT NULL,
  `fechaDeVencimiento` DATE NOT NULL,
  `precio` DECIMAL(12,2) NOT NULL,
  `cantidad_entrante` INT(12) NOT NULL,
  `cantidad_disponible` INT(12) NOT NULL,
  PRIMARY KEY (`id_entradaDeInsumo`),
  INDEX `id_insumo` (`id_insumo` ASC) VISIBLE,
  INDEX `id_entrada` (`id_entrada` ASC) VISIBLE,
  CONSTRAINT `entrada_insumo_ibfk_1`
    FOREIGN KEY (`id_insumo`)
    REFERENCES `jehovarafa`.`insumo` (`id_insumo`),
  CONSTRAINT `entrada_insumo_ibfk_2`
    FOREIGN KEY (`id_entrada`)
    REFERENCES `jehovarafa`.`entrada` (`id_entrada`))
ENGINE = InnoDB
AUTO_INCREMENT = 32
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `jehovarafa`.`factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jehovarafa`.`factura` (
  `id_factura` INT(11) NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `total` FLOAT(12,2) NOT NULL,
  `estado` VARCHAR(10) NOT NULL,
  `serviciomedico_id_servicioMedico` INT(11) NOT NULL,
  PRIMARY KEY (`id_factura`),
  INDEX `fk_factura_serviciomedico1_idx` (`serviciomedico_id_servicioMedico` ASC) VISIBLE,
  CONSTRAINT `fk_factura_serviciomedico1`
    FOREIGN KEY (`serviciomedico_id_servicioMedico`)
    REFERENCES `jehovarafa`.`serviciomedico` (`id_servicioMedico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 57
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `jehovarafa`.`horacostohospitalizacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jehovarafa`.`horacostohospitalizacion` (
  `id_horacostohospitalizacion` INT(11) NOT NULL AUTO_INCREMENT,
  `hora` INT(11) NOT NULL,
  `costo` FLOAT(12,2) NOT NULL,
  PRIMARY KEY (`id_horacostohospitalizacion`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `jehovarafa`.`horario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jehovarafa`.`horario` (
  `id_horario` INT(11) NOT NULL AUTO_INCREMENT,
  `diaslaborables` VARCHAR(100) CHARACTER SET 'latin1' NOT NULL,
  PRIMARY KEY (`id_horario`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `jehovarafa`.`horarioydoctor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jehovarafa`.`horarioydoctor` (
  `id_horarioydoctor` INT(11) NOT NULL AUTO_INCREMENT,
  `id_personal` INT(11) NOT NULL,
  `id_horario` INT(11) NOT NULL,
  `horaDeEntrada` TIME NOT NULL,
  `horaDeSalida` TIME NOT NULL,
  PRIMARY KEY (`id_horarioydoctor`),
  INDEX `id_doctor` (`id_personal` ASC) VISIBLE,
  INDEX `id_horario` (`id_horario` ASC) VISIBLE,
  CONSTRAINT `horarioydoctor_ibfk_1`
    FOREIGN KEY (`id_horario`)
    REFERENCES `jehovarafa`.`horario` (`id_horario`),
  CONSTRAINT `horarioydoctor_ibfk_2`
    FOREIGN KEY (`id_personal`)
    REFERENCES `jehovarafa`.`personal` (`id_personal`))
ENGINE = InnoDB
AUTO_INCREMENT = 30
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `jehovarafa`.`hospitalizacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jehovarafa`.`hospitalizacion` (
  `id_hospitalizacion` INT(11) NOT NULL AUTO_INCREMENT,
  `id_horacostohospitalizacion` INT(11) NOT NULL,
  `duracion` INT(25) NOT NULL,
  `precio_horas` FLOAT NOT NULL,
  `total` FLOAT NOT NULL,
  `historiaclinica` TEXT CHARACTER SET 'latin1' NOT NULL,
  `fecha_hora` DATETIME NOT NULL,
  `estado` VARCHAR(25) CHARACTER SET 'latin1' NOT NULL,
  PRIMARY KEY (`id_hospitalizacion`),
  INDEX `id_horacostohospitalizacion` (`id_horacostohospitalizacion` ASC) VISIBLE,
  CONSTRAINT `hospitalizacion_ibfk_2`
    FOREIGN KEY (`id_horacostohospitalizacion`)
    REFERENCES `jehovarafa`.`horacostohospitalizacion` (`id_horacostohospitalizacion`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `jehovarafa`.`insumodehospitalizacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jehovarafa`.`insumodehospitalizacion` (
  `id_insumoDeHospitalizacion` INT(11) NOT NULL AUTO_INCREMENT,
  `id_hospitalizacion` INT(11) NOT NULL,
  `cantidad` INT(13) NOT NULL,
  PRIMARY KEY (`id_insumoDeHospitalizacion`),
  INDEX `id_hospitalizacion` (`id_hospitalizacion` ASC) VISIBLE,
  CONSTRAINT `insumodehospitalizacion_ibfk_2`
    FOREIGN KEY (`id_hospitalizacion`)
    REFERENCES `jehovarafa`.`hospitalizacion` (`id_hospitalizacion`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `jehovarafa`.`inventario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jehovarafa`.`inventario` (
  `id_inventario` INT(11) NOT NULL AUTO_INCREMENT,
  `id_insumo` INT(11) NOT NULL,
  `cantidad` INT(11) NOT NULL,
  `fachaVencimiento` DATE NOT NULL,
  `numero_de_lote` INT(16) NOT NULL,
  PRIMARY KEY (`id_inventario`),
  INDEX `id_entrada` (`id_insumo` ASC) VISIBLE,
  CONSTRAINT `inventario_ibfk_1`
    FOREIGN KEY (`id_insumo`)
    REFERENCES `jehovarafa`.`insumo` (`id_insumo`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `jehovarafa`.`pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jehovarafa`.`pago` (
  `id_pago` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(25) CHARACTER SET 'latin1' NOT NULL,
  PRIMARY KEY (`id_pago`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `jehovarafa`.`pagodefactura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jehovarafa`.`pagodefactura` (
  `id_pagoDeFactura` INT(11) NOT NULL AUTO_INCREMENT,
  `id_pago` INT(11) NOT NULL,
  `id_factura` INT(11) NOT NULL,
  `referencia` VARCHAR(25) CHARACTER SET 'latin1' NULL DEFAULT NULL,
  `monto` FLOAT(12,2) NOT NULL,
  PRIMARY KEY (`id_pagoDeFactura`),
  INDEX `id_pago` (`id_pago` ASC) VISIBLE,
  INDEX `id_factura` (`id_factura` ASC) VISIBLE,
  CONSTRAINT `pagodefactura_ibfk_1`
    FOREIGN KEY (`id_factura`)
    REFERENCES `jehovarafa`.`factura` (`id_factura`),
  CONSTRAINT `pagodefactura_ibfk_2`
    FOREIGN KEY (`id_pago`)
    REFERENCES `jehovarafa`.`pago` (`id_pago`))
ENGINE = InnoDB
AUTO_INCREMENT = 72
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `jehovarafa`.`patologia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jehovarafa`.`patologia` (
  `id_patologia` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre_patologia` VARCHAR(25) CHARACTER SET 'latin1' NOT NULL,
  `estado` VARCHAR(12) CHARACTER SET 'latin1' NOT NULL,
  PRIMARY KEY (`id_patologia`))
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `jehovarafa`.`patologiadepaciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jehovarafa`.`patologiadepaciente` (
  `id_patologiaDePaciente` INT(11) NOT NULL AUTO_INCREMENT,
  `id_paciente` INT(11) NULL DEFAULT NULL,
  `id_patologia` INT(11) NULL DEFAULT NULL,
  `fecha_registro` DATETIME NOT NULL,
  PRIMARY KEY (`id_patologiaDePaciente`),
  INDEX `id_paciente` (`id_paciente` ASC) VISIBLE,
  INDEX `id_patologia` (`id_patologia` ASC) VISIBLE,
  CONSTRAINT `patologiadepaciente_ibfk_1`
    FOREIGN KEY (`id_patologia`)
    REFERENCES `jehovarafa`.`patologia` (`id_patologia`),
  CONSTRAINT `patologiadepaciente_ibfk_2`
    FOREIGN KEY (`id_paciente`)
    REFERENCES `jehovarafa`.`paciente` (`id_paciente`))
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `jehovarafa`.`recuperar_contr`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jehovarafa`.`recuperar_contr` (
  `id_recuperar_contr` INT(11) NOT NULL AUTO_INCREMENT,
  `id_usuario` INT(11) NOT NULL,
  `codigo` VARCHAR(55) NOT NULL,
  `fecha_expiracion` DATETIME NOT NULL,
  `intentos_fallidos` INT(11) NULL DEFAULT 0,
  `fecha_desbloqueo` DATETIME NOT NULL,
  PRIMARY KEY (`id_recuperar_contr`),
  INDEX `id_usuario` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `recuperar_contr_ibfk_1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `jehovarafa`.`usuario` (`id_usuario`))
ENGINE = InnoDB
AUTO_INCREMENT = 33
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `jehovarafa`.`sintomas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jehovarafa`.`sintomas` (
  `id_sintomas` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(25) NOT NULL,
  `estado` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`id_sintomas`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `jehovarafa`.`sintomas_control`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jehovarafa`.`sintomas_control` (
  `id_sintomas_control` INT(11) NOT NULL AUTO_INCREMENT,
  `id_sintomas` INT(11) NOT NULL,
  `id_control` INT(11) NOT NULL,
  PRIMARY KEY (`id_sintomas_control`),
  INDEX `id_sintomas` (`id_sintomas` ASC) VISIBLE,
  INDEX `id_control` (`id_control` ASC) VISIBLE,
  CONSTRAINT `sintomas_control_ibfk_1`
    FOREIGN KEY (`id_control`)
    REFERENCES `jehovarafa`.`control` (`id_control`),
  CONSTRAINT `sintomas_control_ibfk_2`
    FOREIGN KEY (`id_sintomas`)
    REFERENCES `jehovarafa`.`sintomas` (`id_sintomas`))
ENGINE = InnoDB
AUTO_INCREMENT = 37
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `jehovarafa`.`hospitalizacion_has_serviciomedico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jehovarafa`.`hospitalizacion_has_serviciomedico` (
  `hospitalizacion_id_hospitalizacion` INT(11) NOT NULL,
  `serviciomedico_id_servicioMedico` INT(11) NOT NULL,
  PRIMARY KEY (`hospitalizacion_id_hospitalizacion`, `serviciomedico_id_servicioMedico`),
  INDEX `fk_hospitalizacion_has_serviciomedico_serviciomedico1_idx` (`serviciomedico_id_servicioMedico` ASC) VISIBLE,
  INDEX `fk_hospitalizacion_has_serviciomedico_hospitalizacion1_idx` (`hospitalizacion_id_hospitalizacion` ASC) VISIBLE,
  CONSTRAINT `fk_hospitalizacion_has_serviciomedico_hospitalizacion1`
    FOREIGN KEY (`hospitalizacion_id_hospitalizacion`)
    REFERENCES `jehovarafa`.`hospitalizacion` (`id_hospitalizacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_hospitalizacion_has_serviciomedico_serviciomedico1`
    FOREIGN KEY (`serviciomedico_id_servicioMedico`)
    REFERENCES `jehovarafa`.`serviciomedico` (`id_servicioMedico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `jehovarafa`.`serviciomedico_has_insumo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jehovarafa`.`serviciomedico_has_insumo` (
  `serviciomedico_id_servicioMedico` INT(11) NOT NULL,
  `insumo_id_insumo` INT(11) NOT NULL,
  PRIMARY KEY (`serviciomedico_id_servicioMedico`, `insumo_id_insumo`),
  INDEX `fk_serviciomedico_has_insumo_insumo1_idx` (`insumo_id_insumo` ASC) VISIBLE,
  INDEX `fk_serviciomedico_has_insumo_serviciomedico1_idx` (`serviciomedico_id_servicioMedico` ASC) VISIBLE,
  CONSTRAINT `fk_serviciomedico_has_insumo_serviciomedico1`
    FOREIGN KEY (`serviciomedico_id_servicioMedico`)
    REFERENCES `jehovarafa`.`serviciomedico` (`id_servicioMedico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_serviciomedico_has_insumo_insumo1`
    FOREIGN KEY (`insumo_id_insumo`)
    REFERENCES `jehovarafa`.`insumo` (`id_insumo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `jehovarafa`.`permisos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jehovarafa`.`permisos` (
  `idpermisos` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`idpermisos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jehovarafa`.`rol_has_permisos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jehovarafa`.`rol_has_permisos` (
  `rol_id_rol` INT(11) NOT NULL,
  `permisos_idpermisos` INT NOT NULL,
  PRIMARY KEY (`rol_id_rol`, `permisos_idpermisos`),
  INDEX `fk_rol_has_permisos_permisos1_idx` (`permisos_idpermisos` ASC) VISIBLE,
  INDEX `fk_rol_has_permisos_rol1_idx` (`rol_id_rol` ASC) VISIBLE,
  CONSTRAINT `fk_rol_has_permisos_rol1`
    FOREIGN KEY (`rol_id_rol`)
    REFERENCES `jehovarafa`.`rol` (`id_rol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rol_has_permisos_permisos1`
    FOREIGN KEY (`permisos_idpermisos`)
    REFERENCES `jehovarafa`.`permisos` (`idpermisos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
