<?php


return [
    //Pacientes
    "getPacientes" => "consultar",
    "getPacientesAjax" => "consultar",
    "papeleraPaciente" => "consultar",
    "papeleraPacienteAjax"=> "consultar",
    "guardar" => "guardar",
    "setPaciente"  => "editar",
    "eliminar" => "eliminar",
    "restablecer" => "eliminar",
    "getHistorialSalud" => "consultar",


    //Clientes
    "Clientes" => "consultar",
    "clientesAjax"=>'consultar',
    "papeleraPaciente" => "consultar",
    "papeleraAjax" => "consultar",
    "guardar" => "guardar",
    "setCliente"  => "editar",
    "eliminar" => "eliminar",
    "restablecer" => "eliminar",

    //Patlogias
    "patologias" => "consultar",
    "patologiasAjax" => "consultar",
    "papeleraAjax" => "consultar",
    "papeleraPatologias" => "consultar",
    "registrarPatologia" => "guardar",
    "eliminarPatologia" => "eliminar",
    "restablecerPatologia" => "eliminar",


    //Factura
    "factura" => "consultar",
    "facturaCita" => "consultar",
    "comprobante" => "consultar",
    "mostrarPaciente" => "consultar",
    "mostrarCliente" => "consultar",
    "mostrarPacienteConCita" => "consultar",
    "mostrarTodosLosServicios" => "consultar",
    "mostrarTodosLosDoctores" => "consultar",
    "mostrarPrecio" => "consultar",
    "mostrarNombreTodosDoctores" => "consultar",
    "nombreSegunIdC" => "consultar",
    "nombreSegunIdD" => "consultar",
    "insumosAjax" => "consultar",
    "mostrarPDF" => "consultar",
    "mostrarPDF2" => "consultar",
    "mostrarPDF3" => "consultar",
    "guardarFactura" => "guardar",
    "guardarFacturaHospit" => "guardar",
    "facturarHospitalizacion" => "consultar",
    "coincidenciaPacienteCliente" => "consultar",
    "guardarCliente" => "consultar",

    //Citas
    "mostrarPacienteCita" => "consultar",
    "mostrarPacienteCitaGet" => "consultar",
    "citas" => "consultar",
    "citasAjax" => "consultar",
    "citasHoy" => "consultar",
    "citasHoyAjax" => "consultar",
    "citasP" => "consultar",
    "guardarCita" => "guardar",
    "eliminarCita" => "eliminar",
    "citasHoyP" => "consultar",
    "citasRealizadas" => "consultar",
    "citasRealizadasAjax" => "consultar",
    "mostrarDoctoresCita" => "consultar",
    "mostrarHorario" => "consultar",
    "editarCita" => "editar",
    "insertaPaciente" => "guardar",
    "validarHorariosDisponlibles" => "consultar",


    //Servicios Medicos
    "consultas" => "consultar",
    "categoriasAjax" => "consultar",
    "consultasAjax" => "consultar",
    "papeleraServicio" => "consultar",
    "papeleraAjax"  => "consultar",
    "guardar" => "guardar",
    "eliminar" => "eliminar",
    "restablecer" => "restablecer",
    "editar" => "editar",
    "mostrarEspecialidad" => "consultar",
    "registrarCategoria" => "guardar",
    "eliminarCategoria" => "eliminar",
    "serviciosDoctor" => "consultar",
    "restablecer" => "eliminar",


    //Doctores
    "doctores" => "consultar",
    "DoctoresAjax"=> "consultar",
    "agregarDoctor" => "guardar",
    "editarDoctor" => "editar",
    "borrarDoctor" => "eliminar",
    "selectDiasDoctorEditar" => "consultar",
    "registrarEspecialidad" => "guardar",
    "EliminarEspecialidad" => "eliminar",
    "buscarEspecialidad" => "consultar",
    "buscarDoctor" => "consultar",
    "buscarHorario" => "consultar",
    "guardarDoctores" => "guardar",
    "selectEspcAjax"=>"guardar",
    "eliminarEspecialidad" => "consultar",

    //Usuarios
    "usuarios" => "consultar",
    "usuariosAjax" => "consultar",
    "administradores" => "consultar",
    "administradoresAjax" => "consultar",
    "papeleraUsuario" => "consultar",
    "registrarAdmin" => "guardar",
    "editarAdministrador" => "editar",
    "eliminarAdministrador" => "eliminar",
    "editarUsuario" => "editar",
    "borrarUsuario" => "eliminar",
    "registrarAdmin" => "guardar",
    "buscarUsuario" => "consultar",
    "buscarUsuarioAdmin" => "consultar",
    "editarAdministrador" => "editar",
    "eliminarAdministrador" => "eliminar",
    "verificarPassw" => "consultar",

    //Hospitalizacion
    "serviciosDH" => "consultar",
    "selectDoctores" => "consultar",
    "selectServiciosD" => "consultar",
    "traerSesion" => "consultar",
    "traerSesionR" => "consultar",
    "hospitalizacion" => "consultar",
    "hospitalizacionesRealizadas" => "consultar",
    "validarPaciente"  => "consultar",
    "validarControl" => "consultar",
    "mostrarInformacionPCD" => "consultar",
    "mostrarInsumos" => "consultar",
    "mostrarUnInsumo" => "consultar",
    "agregarH" => "guardar",
    "traerInsuDHEd" => "consultar",
    "modificarH" => "editar",
    "eliminaL" => "eliminar",
    "enviarAFacturar" => "guardar",
    "buscarIExH" => "consultar",


    //Control
    "control" => "consultar",
    "mostrarBusquedaPacientesJS" => "consultar",
    "mostrarControlPacientesJS" => "consultar",
    "mostrarPacienteJS" => "consultar",
    "insertarControl" => "guardar",
    "eliminarControl" => "eliminar",
    "editarControl" => "editar",
    "mostrarSP" => "consultar",
    "mostrarPP" => "consultar",
    "mostrarPIdP" => "consultar",
    "eliminarSintoma" => "eliminar",
    "agregarSintoma" => "editar",
    "listPacientesJS" => "consultar",

    //Insumos
    "insumos" => "consultar",
    "vencidos" => "consultar",
    "insumosAjax" => "consultar",
    "retornarLasEntradas" => "consultar",
    "InsumosVencidos" => "consultar",
    "info" => "consultar",
    "mostrarBusquedaInsumo" => "consultar",
    "papelera" => "consultar",
    "papeleraInsumosAjax" => "consultar",
    "guardarInsumo" => "guardar",
    "editar" => "editar",
    "eliminar" => "eliminar",
    "restablecerInsumo" => "eliminar",
    "cantidadInsumos" => "consultar",
    "cantidadInsumosVencidos" => "consultar",

    //Entrada
    "entrada" => "consultar",
    "entradasAjax" => "consultar",
    "entradasPapeleraAjax" => "consultar",
    "papelera" => "consultar",
    "guardar" => "guardar",
    "eliminar" => "eliminar",
    "editar" => "editar",
    "entradaInsumo" => "consultar",
    "restablecerEntrada" => "eliminar",
    "proveedoresEditar" => "consultar",
    "selectProveedores" => "consultar",
    "selectInsumos" => "consultar",
    "selectInsumosEditar" => "consultar",


    //Proveedores
    "proveedores" => "consultar",
    "proveedoresAjax" => "consultar",
    "papelera" => "consultar",
    "proveedoresPapeleraAjax" => "consultar",
    "insertar" => "guardar",
    "update" => "eliminar",
    "restablecerProveedor" => "eliminar",
    "editar" => "editar",
    "validarRif" => "consultar",
    "validarRifEditar" => "consultar",
    "buscarProveedor" => "consultar",


    //Roles
    "mostrar" => "consultar",
    "mostrarAjax" => "consultar",
    "mostrarPermisos" => "consultar",
    "guardarRol" => "guardar",
    "modificarRol" => "editar",
    "eliminarRol" => "eliminar",
    "validarRol" => "consultar",

    //Reportes
    "reportes" => "consultar",
    "buscarPDF" => "consultar",
    "buscarEntradasInsumosPDF" => "consultar",
    "factura" => "consultar",
    "pacientePDF" => "consultar",
    "insumosPDF" => "consultar",
    "reportesFactura" => "consultar",
    "reportesFacturasAnuladas" => "consultar",
    "buscarPago" => "consultar",
    "buscarMasServicios" => "consultar",
    "buscarInsumos" => "consultar",
    "buscarCita" => "consultar",
    "buscarCitaPDF" => "consultar",
    "anularFactura" => "eliminar",


    //Reportes Estadisticos
    "estadisticas" => "consultar",
    "edadGenero" => "consultar",
    "tasaMorbilidad" => "consultar",
    "filtrar_tasaMorbilidad" => "consultar",
    "insumos" => "consultar",

    //Mantenimiento
    "mantenimiento" => "consultar",
    "bajarBdsNube" => "consultar",
    "consultarBd" => "consultar",
    "generarRespaldo" => "guardar",
    "restaurarRespaldo" => "guardar",
    "verificacionU" => "consultar",

];
